version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/minsocial
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=techschool.settings
      - ALLOWED_HOSTS=mintechy.pythonanywhere.com  # Set your allowed host here
