# Generated by Django 4.1.7 on 2023-07-29 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_userComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_postComment', to='minsocial.grouppost'),
        ),
        migrations.AlterField(
            model_name='grouphaha',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_postHaha', to='minsocial.grouppost'),
        ),
        migrations.AlterField(
            model_name='grouplike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_like', to='minsocial.grouppost'),
        ),
        migrations.AlterField(
            model_name='grouplove',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_postLove', to='minsocial.grouppost'),
        ),
        migrations.AlterField(
            model_name='groupsad',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_postSad', to='minsocial.grouppost'),
        ),
        migrations.AlterField(
            model_name='groupshock',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_postShock', to='minsocial.grouppost'),
        ),
    ]
