# Generated by Django 4.1.7 on 2023-08-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0004_remove_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('postContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_images', to='minsocial.post')),
            ],
        ),
    ]
