# Generated by Django 4.1.7 on 2023-08-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0005_grouppostimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='post_image',
        ),
    ]
