# Generated by Django 4.1.7 on 2023-07-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0005_forumtopic_forumpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='minsocial.forumtopic'),
        ),
    ]
