# Generated by Django 4.1.7 on 2023-07-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image/'),
        ),
    ]
