# Generated by Django 4.1.7 on 2023-08-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0007_alter_grouppostimage_postcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_post_images', to='minsocial.grouppost')),
            ],
        ),
    ]
