# Generated by Django 4.1.7 on 2023-07-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0008_announcement_announcement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement_image',
            new_name='post_image',
        ),
    ]
