# Generated by Django 4.1.7 on 2023-07-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0009_rename_announcement_image_announcement_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='post_image',
            new_name='announcement_image',
        ),
    ]
