# Generated by Django 4.1.7 on 2023-08-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0010_alter_announcementpostimage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_post_images', to='minsocial.forumtopic')),
            ],
        ),
    ]
