# Generated by Django 4.1.7 on 2023-08-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0012_video_viewers_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='viewers_ip',
        ),
    ]
