# Generated by Django 4.2.4 on 2023-09-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0015_librarydocument_viewers_ip_librarydocument_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minsocial.librarycategory')),
            ],
        ),
    ]
