# Generated by Django 4.2.4 on 2023-09-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0016_libraryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycategory',
            name='categoryName',
            field=models.CharField(choices=[('Science', 'Science'), ('IT', 'IT'), ('Math', 'Math'), ('Skills and Self-growth', 'Skills and Self-growth'), ('Agriculture', 'Agriculture'), ('Finance', 'Finance'), ('Economics', 'Economics'), ('Philosophy', 'Philosophy'), ('Others', 'Others')], max_length=50),
        ),
    ]
