# Generated by Django 4.2.4 on 2023-09-06 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0017_alter_librarycategory_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryimage',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraryimage_set', to='minsocial.librarycategory'),
        ),
    ]
