# Generated by Django 4.2.4 on 2023-09-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0019_post_shared_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_by',
        ),
    ]
