# Generated by Django 4.2.4 on 2023-09-23 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0021_sharepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.group'),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='group_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.grouppost'),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
