# Generated by Django 4.2.4 on 2023-09-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0024_sharepost_shared_sharepost_shared_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='shared_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.post'),
        ),
    ]
