# Generated by Django 4.2.4 on 2023-09-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0028_alter_sharepost_shared_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharePost',
        ),
    ]
