# Generated by Django 4.2.4 on 2023-09-28 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0029_delete_sharepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=True)),
                ('shared_post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.post')),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
