# Generated by Django 4.2.4 on 2023-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0030_sharepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
