# Generated by Django 4.2.4 on 2023-09-28 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0031_alter_sharepost_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharepost',
            name='shared',
        ),
        migrations.AddField(
            model_name='sharepost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
