# Generated by Django 4.2.4 on 2023-09-28 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0032_remove_sharepost_shared_sharepost_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharepost',
            old_name='timestamp',
            new_name='timestamps',
        ),
    ]
