# Generated by Django 4.2.4 on 2023-09-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0033_rename_timestamp_sharepost_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharepost',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
