# Generated by Django 4.2.4 on 2023-09-28 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0035_sharepost_shared_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.post')),
                ('shared_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.group')),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
