# Generated by Django 4.2.4 on 2023-09-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0041_alter_groupshare_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='groupshare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.groupshare'),
        ),
        migrations.AlterField(
            model_name='groupshare',
            name='shared_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.post'),
        ),
    ]
