# Generated by Django 4.2.4 on 2023-09-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minsocial', '0043_remove_grouppost_groupshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='groupshare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minsocial.groupshare'),
        ),
    ]
