from django.contrib import admin
from .models import *
# Register your models here

admin.site.register(User)
admin.site.register(Announcement)
admin.site.register(LibraryCategory)
admin.site.register(LibraryDocument)
admin.site.register(Video)
admin.site.register(FavoriteDocument)
admin.site.register(FavoriteVideo)
admin.site.register(ForumPost)
admin.site.register(ForumTopic)
admin.site.register(Follow)
admin.site.register(Post)
admin.site.register(Comment)
admin.site.register(Like)
admin.site.register(Sad)
admin.site.register(Love)
admin.site.register(Haha)
admin.site.register(Shock)
admin.site.register(Group)
admin.site.register(GroupPost)
admin.site.register(GroupComment)
admin.site.register(GroupLike)
admin.site.register(GroupSad)
admin.site.register(GroupLove)
admin.site.register(GroupHaha)
admin.site.register(GroupShock)
